name: Weekly Admin Check

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  check-admins:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Increase this if necessary

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install python-hcl2 PyGithub
        python -m pip install --upgrade pip

    - name: Run check_admins script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python utils/check_admins.py
