name: Weekly Admin Access Report

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Run the script
        run: |
          chmod +x ./utils/admins.sh
          ./utils/admins.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
